### PR TITLE
Added v2_02_188 attributes

### PR DESCRIPTION
**Pull request by RoeeFabrikant**
lib/lvm/attributes/2.02.188(2)/lvs.yaml    | 328 +++++++++++++++++++++++++++++
 lib/lvm/attributes/2.02.188(2)/lvsseg.yaml | 138 ++++++++++++
 lib/lvm/attributes/2.02.188(2)/pvs.yaml    | 113 ++++++++++
 lib/lvm/attributes/2.02.188(2)/pvsseg.yaml |  16 ++
 lib/lvm/attributes/2.02.188(2)/vgs.yaml    | 140 ++++++++++++
 5 files changed, 735 insertions(+)

Signed-off-by: Roee Fabrikant <roee73@gmail.com>

### Description

[Please describe what this change achieves]

### Issues Resolved

[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant]

### Check List

- [ ] New functionality includes tests
- [ ] All tests pass
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [ ] PR title is a worthy inclusion in the CHANGELOG

### CODE REVIEW

**Review by ramereth — APPROVED** [review]

**Comment by roee73** [comment]
Hi @ramereth 
Do you know how to speed up the review?
Thanks

**Comment by computersalat** [comment]
Is someone willing to `approve` and `merge` please ?
Thank you very much. :-)

**Comment by ramereth** [comment]
@computersalat sorry for the delay. This repo was recently transferred to Sous Chefs and I'm working on getting the new release process nailed down.

**Comment by computersalat** [comment]
> @computersalat sorry for the delay. This repo was recently transferred to Sous Chefs and I'm working on getting the new release process nailed down.

Hmmm ... I see, but isn't the release process independent of the decision if you accept/merge a PR ?

**Pull request merged**
