### PR TITLE
Lvm 2.03.16(2)

### LINKED ISSUE #44: LVM 2.03.16 released
### Describe the Enhancement:
RHEL  9.1 uses LVM 2.03.16

### Describe the Need:
Support for latest LVM

### Current Alternative
No

### Can We Help You Implement This?:
Update latest version support

### PR DESCRIPTION
**Pull request by schrd**
### Description

To bring up the soon to be released Debian 12 we need LVM cookbook support. Looks like RHEL 9 also uses this LVM version.

### Issues Resolved

closes #44 

### Check List

- [ ] New functionality includes tests
- [x] All tests pass
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>
- [x] PR title is a worthy inclusion in the CHANGELOG

### CODE REVIEW

**Comment by ianl678** [comment]
Also required for RHEL 8.7, any progress is getting it merged?

**Review by ramonzumstein — APPROVED** [review]
Update looks good.

**Comment by schrd** [comment]
Hi @ramereth,

is there a chance to get this merged and a new release? If there is something I need to changel, please let me know.

Thank you

**Comment by ramereth** [comment]
@schrd sorry for the delay! Released as 0.3.12.

**Pull request merged**
