### PR TITLE
chore(main): release 0.4.1

### PR DESCRIPTION
**Pull request by kitchen-porter**
:robot: I have created a release *beep* *boop*
---

### Bug Fixes

* Fix release-config ([#66](https://github.com/sous-chefs/chef-ruby-lvm-attrib/issues/66)) ([53c59f1](https://github.com/sous-chefs/chef-ruby-lvm-attrib/commit/53c59f1180d03c74dd5513e2f3a6704597d9581c))
* More ([#68](https://github.com/sous-chefs/chef-ruby-lvm-attrib/issues/68)) ([3c82993](https://github.com/sous-chefs/chef-ruby-lvm-attrib/commit/3c829930cdf73900a6b13eb77a452a0a4cee1d26))
* release-please-config ([#69](https://github.com/sous-chefs/chef-ruby-lvm-attrib/issues/69)) ([e6ea516](https://github.com/sous-chefs/chef-ruby-lvm-attrib/commit/e6ea516797839857aeea1e77186ce27b21b02dd5))

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Comment by damacus** [comment]
@ecottom looks like it still isn't bumping the version file? 🤔

**Comment by ecottom** [comment]
Something else might also be going on. I synced my fork with sous-chefs/chef-ruby-lvm-attrib/main and ran `release-please release-pr --token=$env:myaccesstoken --repo-url=ecottom/chef-ruby-lvm-attrib --target-branch=main` and it did open a [PR](https://github.com/ecottom/chef-ruby-lvm-attrib/pull/1/files) with a bumped version.

**Comment by awrel34** [comment]
Hello, 
would it be possible to release manually to rubygems while debugging the github actions ?

**Comment by awrel34** [comment]
@damacus @ecottom 
Hello ! Any news on this please ?

**Comment by Stromweld** [comment]
closing this PR in favor of #75

**Pull request closed without merging**
